-- AlterTable
ALTER TABLE `order_events` MODIFY `status` ENUM('PAYMENT_DONE', 'PENDING', 'PACKING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RQUEST_REFUND', 'REFUND_DONE') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('PAYMENT_DONE', 'PENDING', 'PACKING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RQUEST_REFUND', 'REFUND_DONE') NOT NULL DEFAULT 'PENDING';
